default:
  dir: \
  input:
    bands:
      1: group_1_band_depth
      2: group_1_mineral_id
      3: group_2_band_depth
      4: group_2_mineral_id
    rename:
      y: latitude
      x: longitude
    file: ${.dir}/EMIT_L2B_MIN_001_20231015T215344_2328814_020.nc
  classify:
    group_1_mineral_id:
      filter: group_1_band_depth > .001
      default: .nan
    group_2_mineral_id:
      filter: group_2_band_depth > .001
      default: .nan
  output:
    merge: false
    geotiff:
      crs: epsg:4326
    netcdf: false

full:
  hashmap: # Minerals mapping
    1: [10]
    2: [9, 15, 49, 204, 205, 206]
    3: [3, 5, 6, 7, 8, 9, 18]
    4: [30, 31, 32, 33, 45, 47]
    5: [11]
    6: [67]
  colors:
    #  [R, G, B, A]
    1: [255, 1, 1, 255]
    2: [1, 255, 1, 255]
    3: [1, 1, 255, 255]
    4: [255, 255, 1, 255]
    5: [1, 255, 255, 255]
    6: [255, 1, 255, 255]

local:
  dir: \
  output:
    dir: ./output

quiet:
  log:
    terminal: INFO

# ALUM GULCH, LEAD QUEEN
loc1:
  subselect:
    latitude: [31.45, 31.55]
    longitude: [-110.8, -110.7]

g1:
  hashmap:
    1: [10]

g2:
  hashmap:
    2: [9, 15, 49, 204, 205, 206]

g3:
  hashmap:
    3: [3, 5, 6, 7, 8, 9, 18]

g4:
  hashmap:
    4: [30, 31, 32, 33, 45, 47]

g5:
  hashmap:
    5: [11]

g6:
  hashmap:
    6: [67]

cluster:
  dir: /scratch/jamesmo/amd/data/mosaics/glts_5_cloudy_20240120_global/l2b/
  output:
    dir: /scratch/jamesmo/amd/data/mosaics/output/v1

mosaic:
  input:
    file: ${.dir}/*

v1:
  hashmap: # Minerals mapping
    1: [10] # pyrite
    2: [3, 5, 6, 7, 8, 9, 18] # goethite
    3: [30, 31, 32, 33, 45, 47] # hematite
    4: [9, 15, 49, 204, 205, 206] # jarosite
    5: [11] # schwertmannite
    6: [67] # copiapite
    7: [126, 184, 211, 212, 213, 214, 215, 216, 217, 218, 219, 225, 226, 227, 229, 230, 231, 232] # Ca,Mg-carbonates
    8: [58, 63, 64, 220, 240, 241, 267, 270, 271] # other carboantes
    9: [93, 153, 154, 155, 156, 237, 287] # Ca,Mg,Al (hydr)oxides
    10: [17, 27, 38, 125, 127, 128, 129, 130, 131, 132, 177, 178, 189, 190, 202] # soluble silicates (+ phosphates)
  colors:
    3: [209, 187, 215, 255]
    2: [174, 118, 163, 255]
    10: [136, 46, 114, 255]
    9: [25, 101, 176, 255]
    8: [82, 137, 199, 255]
    7: [123, 175, 222, 255]
    6: [247, 240, 87, 255]
    5: [246, 193, 65, 255]
    4: [241, 147, 45, 255]
    1: [220, 5, 12, 255]

v2:
  classify:
    group_1_mineral_id:
      filter: group_1_band_depth > .01
    group_2_mineral_id:
      filter: group_2_band_depth > .01
  output:
    dir: /scratch/jamesmo/amd/data/mosaics/output/v2
