default:
  dir: \
  input:
    bands:
      1: group_1_band_depth
      2: group_1_mineral_id
      3: group_2_band_depth
      4: group_2_mineral_id
    rename:
      y: latitude
      x: longitude
    file: ${.dir}/EMIT_L2B_MIN_001_20231015T215344_2328814_020.nc
  classify:
    group_1_mineral_id:
      filter: group_1_band_depth > .001
      default: .nan
    group_2_mineral_id:
      filter: group_2_band_depth > .001
      default: .nan
  output:
    merge: true
    geotiff:
      crs: epsg:4326
    netcdf: true

full:
  hashmap: # Minerals mapping
    1: [10]
    2: [9, 15, 49, 204, 205, 206]
    3: [3, 5, 6, 7, 8, 9, 18]
    4: [30, 31, 32, 33, 45, 47]
    5: [11]
    6: [67]
  colors:
    #  [R, G, B, A]
    1: [255, 1, 1, 255]
    2: [1, 255, 1, 255]
    3: [1, 1, 255, 255]
    4: [255, 255, 1, 255]
    5: [1, 255, 255, 255]
    6: [255, 1, 255, 255]

local:
  dir: /path/to/your/input/data
  output:
    dir: ./output

quiet:
  log:
    terminal: INFO

# ALUM GULCH, LEAD QUEEN
loc1:
  subselect:
    latitude: [31.45, 31.55]
    longitude: [-110.8, -110.7]

g1:
  hashmap:
    1: [10]

g2:
  hashmap:
    2: [9, 15, 49, 204, 205, 206]

g3:
  hashmap:
    3: [3, 5, 6, 7, 8, 9, 18]

g4:
  hashmap:
    4: [30, 31, 32, 33, 45, 47]

g5:
  hashmap:
    5: [11]

g6:
  hashmap:
    6: [67]
